### ISSUE TITLE
ASTC file generation

### ISSUE THREAD

**Issue by jblazeg** [RudolphRiedel/EVE_ASTC_Test_Arduino_PlatformIO#1]
I try to generate a ASTC file for pushing it into the flash. There is the EVE Asset Builder (EAB) but I'm more looking into a commandline tool.

When using EAB I can see, it utilises "astcenc.exe". But the file comparison between an EAB generated file and an own one looks totally different. Any hints?

**Comment by RudolphRiedel** [comment]
I am only using the EAB GUI to convert images and fonts.
But I believe what you are looking for is the "eab_tools.exe" in the "tools" dir of EAB.

And the correct place to ask something like this would have been here:
https://github.com/RudolphRiedel/FT800-FT813/discussions :-)
